services:
  - type: web
    name: galaxia-te-amo
    env: static
    staticPublishPath: .
    headers:
      - path: /*
        name: Content-Security-Policy
        value: "default-src 'self'; script-src 'self' 'unsafe-inline' https://www.googletagmanager.com https://cdn.jsdelivr.net; connect-src 'self' https://www.google-analytics.com https://region1.google-analytics.com; img-src 'self' data: https://www.google-analytics.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; media-src 'self' https://github.com https://raw.githubusercontent.com;"
      - path: /*
        name: X-Content-Type-Options
        value: "nosniff"
      - path: /*
        name: X-Frame-Options
        value: "DENY"
      - path: /*
        name: Referrer-Policy
        value: "strict-origin-when-cross-origin"